#!/bin/bash

HEIGHT=15
WIDTH=100
CHOICE_HEIGHT=4
BACKTITLE="Geiles homeean Installationstool"
TITLE="Das wird Mega"
MENU="Was möchtest du installieren? Für Node-Red und Homebridge bitte zuerst NodeJS zu den Paketquellen hinzufügen :"

OPTIONS=(1 "NodeJS zu Paketquellen hinzufügen"
         2 "Homebridge mit homee-Plugin"
         3 "Node-Red mit homee-Plugin"
         4 "Option 4")
        
clear

sudo apt-get update && sudo apt-get upgrade && sudo apt-get install dialog &&
function menu {
CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            stage1
            
            
            ;;
        2)
            stage2
            ;;
        3)
            stage3
            
            ;;
        4)
            stage4
            
            ;;
esac

}

function stage1 {
            echo "Paketquellen anpassen"
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
menu
}

function stage2 {
            echo "Homebridge und homee-Plugin inkl. Autostart wird installiert"
            sudo apt-get install -y nodejs && sudo apt-get install -y build-essential && sudo apt-get install libavahi-compat-libdnssd-dev && sudo npm install -g homebridge --unsafe-perm && sudo npm install -g homebridge-homee && sudo cp homebridge.service /etc/systemd/system/ && sudo systemctl daemon-reload && sudo systemctl enable homebridge && sudo systemctl start homebridge
            
menu
}

function stage3 {
            echo "Node-Red mit homee-Plugin inkl. Autostart"
            sudo apt-get install -y nodejs && sudo apt-get install -y build-essential && sudo npm install -g node-red --unsafe-perm && node-red && ps -ef | grep node-red | awk '{print $2}' | sudo xargs kill && sudo cp node-red /etc/init.d/ && sudo update-rc.d node-red defaults && npm install node-red-contrib-homee
            
menu
}
function stage4 {
            echo "You chose Option 4"
menu
}
menu